language: android
jdk: oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.0.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21

env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

before_install:
  # Gradle 2.1
  - wget http://services.gradle.org/distributions/gradle-2.1-bin.zip
  - unzip gradle-2.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - export  KEYSTORE=$HOME/snowdream.keystore
  - export  KEYSTORE_PASSWORD=1234567
  - export  KEY_ALIAS=snowdream
  - export  KEY_PASSWORD=1234567

  # environment info
  - gradle -v

before_script:
  # write gradle.properties
  - wget https://gist.githubusercontent.com/snowdream/8120098/raw/b995fd8ef78499e5b57aa3fd3fb7525545c43687/gradle.properties -O  $HOME/.gradle/gradle.properties
  - wget https://raw.githubusercontent.com/SnowdreamFramework/android-gradle-template/develop/snowdream.keystore -O  $HOME/snowdream.keystore
  - wget https://raw.githubusercontent.com/SnowdreamFramework/android-gradle-template/develop/secring.gpg -O  $HOME/secring.gpg


  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - TERM=dumb gradle build connectedCheck
