language: android
jdk: oraclejdk7

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.0.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-x86-android-21

env:
  matrix:
    - ANDROID_SDKS=android-21,sysimg-21  ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

before_install:
  # Gradle
  - wget http://services.gradle.org/distributions/gradle-2.1-bin.zip
  - unzip gradle-2.1-bin.zip
  - export GRADLE_HOME=$PWD/gradle-2.1
  - export PATH=$GRADLE_HOME/bin:$PATH

  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

before_script:
  - chmod +x ci/wait_for_emulator.sh
  - ci/wait_for_emulator.sh
  - adb shell input keyevent 82 &

script:
  - TERM=dumb gradle build connectedCheck
